### ISSUE TITLE
Regarding the using of 'dispatch' in the action function

### ISSUE THREAD

**Issue by burekas7** [Bilal-Bangash/redux-hooks#1]
Hi,

I found your example and it is very nice, thanks.

I have a question regarding your Action code.
Why do you run the dispatch function also in the action.
Actually it runs twice, first time in the component and second time in the action.
It should run only in the component with the action function, isn't it?
What is the purpose of running in also in the action?

And by the way, how does the action code know what are 'dispatch' and 'getState'?
You pass only the 'firstName' from the component dispatch as an argument with the action. 

Your code is like this:
```
export const updateFirstName = (firstName) => (dispatch, getState) => {
  try {
    console.log(firstName, getState());
    dispatch({
      type: SET_FIRST_NAME,
      payload: {
        firstName,
        message: `Update Firstname ${
          getState().nameReducer.firstName
        } to ${firstName} `,
      },
    });
  } catch (error) {
    console.log("Error", error);
  }
};
```

Why didn't you code it like this:
```
export const updateFirstName = (firstName) => {
  return {
      type: SET_FIRST_NAME,
      payload: firstName
    }
}
```

Thanks.

**Comment by Bilal-Bangash** [comment]
> Hi,
> 
> I found your example and it is very nice, thanks.
> 
> I have a question regarding your Action code. Why do you run the dispatch function also in the action. Actually it runs twice, first time in the component and second time in the action. It should run only in the component with the action function, isn't it? What is the purpose of running in also in the action?
> 
> And by the way, how does the action code know what are 'dispatch' and 'getState'? You pass only the 'firstName' from the component dispatch as an argument with the action.
> 
> Your code is like this:
> 
> ```
> export const updateFirstName = (firstName) => (dispatch, getState) => {
>   try {
>     console.log(firstName, getState());
>     dispatch({
>       type: SET_FIRST_NAME,
>       payload: {
>         firstName,
>         message: `Update Firstname ${
>           getState().nameReducer.firstName
>         } to ${firstName} `,
>       },
>     });
>   } catch (error) {
>     console.log("Error", error);
>   }
> };
> ```
> 
> Why didn't you code it like this:
> 
> ```
> export const updateFirstName = (firstName) => {
>   return {
>       type: SET_FIRST_NAME,
>       payload: firstName
>     }
> }
> ```
> 
> Thanks.

```
export const updateFirstName = (firstName) => (dispatch, getState) => {
  try {
    console.log(firstName, getState());
    dispatch({
      type: SET_FIRST_NAME,
      payload: {
        firstName,
        message: `Update Firstname ${
          getState().nameReducer.firstName
        } to ${firstName} `,
      },
    });
  } catch (error) {
    console.log("Error", error);
  }
};
```


Purpose of above code ===>
calling again dispatch function in an action to execute specific type in reducer and also pass data (payload) to that specific type to update store.
If you check the reducer file there are some cases you can understand easily, please.

and this code means
```
export const updateFirstName = (firstName) => {
  return {
      type: SET_FIRST_NAME,
      payload: firstName
    }
}
```
here you are returning an object rather than executing any type in reducer

Hope the above answer will help. If you need any further explanation to let me know, please
Thanks :)

**Comment by Bilal-Bangash** [comment]
@burekas7 more about [Redux Thunk ](https://redux.js.org/usage/writing-logic-thunks) here....

**Comment by burekas7** [comment]
Thanks.
I will read about the Redux Thunk.

But why did you said that the short code doesn't execute and type in the reducer?
You do execute the "dispatch" in the component code.

I see some other examples without the Redux Thunk, and it works the same.
So why do I need it here?

**Comment by Bilal-Bangash** [comment]
> return {
>       type: SET_FIRST_NAME,
>       payload: firstName
>     }

Did you run code locally??
I implemented a bit differently you can directly execute any action for updating store data.
But in my case, I created an action function and from that action function, I am dispatching type to update store in reducers.


In my scenario, I call action function from component and do some work in action function and pass that updated data of specific type to the reducer


component=>dispatch(actionfunction)===in actionfunction did some logical work on data etc and then => dispatch(type and pass data forward)=> in reducers you can check there are some cases/types and the type we received execute that in reducers and update store data
